This dataset was part of competetion problem I had faced ,This was my first model I have built from scratch so please mind the errors.

Understanding uptill now :

We have few rows with missing is_goal data which is our test data. We have to predict the probaability for the missing rows is_goal column with our machine learnign model

The data we will use for train is the rows which are having any particular value of is_goal present.

Now once we have segregated the train data and test data.

We will divide our data into X, y i.e input and output set, -->So we will put the output Y column as is_goal and for -->Other columns will be our input X.

Now as the data we have in X constitutes of the columns with different data types , so we would require to do some exploratory data analysis before we could make use of the same in our model.

The first thing is that : the columns pertaining to numerical value have a lot of Null(NAN) values present in them, we tend to use filler functions to treat them first like FillNa() to fill the null values with the mean average or some by default value or we can simply drop them altogether but that might lead to loss of data.

Note : We can also use SimpleImputer to transform our data .

question for myself? We are doing above steps in the hope of having better performance on our system i,e lesser mean absolute error, mean squared error or whichever evaluation metric we are using . or is it a necessity to implicate our Data into Ml Model that is it won't be working with NAN values or throwing.

okay so once we have treated the null values with our imputer/fillna for numerical or i.e non object data type then we can work over our categorical features .

As the categorical variable data also possesss significant amout of business information it would very much apt to bring our categorical into numerical so that they can inculcated to be included into our model.

We have tried using label encoder for our data which will encode each of the term with a numerical value and i have seen mean absolute error for my model hasn't reduced much after using it.

For using label encoder I have filtered categorical variables and the variables with the data set similar in train , validation and test are good to be taken for label encoding.

In [3]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import Imputer
from sklearn.metrics import mean_absolute_error
from xgboost import XGBRegressor

data = pd.read_csv('data.csv',index_col=0)

data['shot_id_number'] = data.index + 1  # shot id number has null value

sample = pd.read_csv('sample_submission.csv',index_col=0)

data_train_test_combined =  data[data['is_goal'].notnull()]
test_file = data[data['is_goal'].isnull()]

In [9]:
data_train_test_combined

,match_event_id,location_x,location_y,remaining_min,power_of_shot,knockout_match,game_season,remaining_sec,distance_of_shot,is_goal,...,lat/lng,type_of_shot,type_of_combined_shot,match_id,team_id,remaining_min.1,power_of_shot.1,knockout_match.1,remaining_sec.1,distance_of_shot.1
1,12.0,-157.0,0.0,10.0,1.0,0.0,2000-01,22.0,35.0,0.0,...,"45.539131, -122.651648",shot - 45,NaN,20000012,1610612747,10.00,1.00,28.800,22.0000,35.000
2,35.0,-101.0,135.0,7.0,1.0,0.0,2000-01,45.0,36.0,1.0,...,"45.539131, -122.651648",shot - 25,NaN,20000012,1610612747,92.64,1.00,0.000,63.7216,54.400
3,43.0,138.0,175.0,6.0,1.0,0.0,2000-01,52.0,42.0,0.0,...,"45.539131, -122.651648",NaN,shot - 3,20000012,1610612747,NaN,1.00,122.608,52.0000,42.000
4,155.0,0.0,0.0,NaN,2.0,0.0,2000-01,19.0,20.0,1.0,...,"45.539131, -122.651648",NaN,shot - 1,20000012,1610612747,42.64,2.00,0.000,19.0000,20.000
5,244.0,-145.0,-11.0,9.0,3.0,0.0,NaN,32.0,34.0,0.0,...,"45.539131, -122.651648",shot - 17,NaN,20000012,1610612747,9.00,3.00,0.000,NaN,34.000
6,251.0,0.0,0.0,8.0,NaN,0.0,2000-01,52.0,20.0,1.0,...,"45.539131, -122.651648",NaN,shot - 4,20000012,1610612747,8.00,3.00,0.000,112.2000,89.400
8,265.0,-65.0,NaN,6.0,3.0,0.0,2000-01,12.0,32.0,1.0,...,"45.539131, -122.651648",shot - 36,NaN,20000012,1610612747,6.00,3.00,0.000,12.0000,32.000
9,294.0,-33.0,NaN,3.0,3.0,0.0,2000-01,36.0,32.0,0.0,...,"45.539131, -122.651648",shot - 44,NaN,20000012,1610612747,3.00,3.00,0.000,52.2000,NaN
10,309.0,-94.0,238.0,1.0,3.0,0.0,2000-01,56.0,45.0,0.0,...,"45.539131, -122.651648",shot - 7,NaN,20000012,1610612747,NaN,3.00,80.928,56.0000,45.000
11,4.0,121.0,127.0,11.0,1.0,0.0,2000-01,0.0,37.0,1.0,...,"42.982923, -71.446094",NaN,shot - 3,20000019,1610612747,11.00,1.00,106.608,64.7856,16.400
12,27.0,-67.0,NaN,7.0,1.0,0.0,NaN,NaN,NaN,1.0,...,"42.982923, -71.446094",shot - 44,NaN,20000019,1610612747,7.00,77.36,0.000,9.0000,32.000
13,66.0,-94.0,4.0,NaN,1.0,0.0,2000-01,44.0,29.0,0.0,...,"42.982923, -71.446094",NaN,shot - 3,20000019,1610612747,2.00,68.36,0.000,44.0000,29.000
14,80.0,-23.0,47.0,1.0,1.0,0.0,2000-01,16.0,25.0,0.0,...,"42.982923, -71.446094",shot - 12,NaN,20000019,1610612747,1.00,1.00,0.000,16.0000,25.000
15,86.0,NaN,192.0,0.0,1.0,0.0,2000-01,NaN,40.0,0.0,...,"42.982923, -71.446094",NaN,shot - 3,20000019,1610612747,94.64,70.36,0.000,70.7856,40.000
17,138.0,-117.0,226.0,8.0,2.0,0.0,2000-01,50.0,45.0,1.0,...,"42.982923, -71.446094",shot - 6,NaN,20000019,1610612747,38.64,2.00,0.000,50.0000,NaN
18,244.0,NaN,97.0,11.0,3.0,0.0,2000-01,29.0,36.0,0.0,...,"42.982923, -71.446094",NaN,shot - 3,20000019,1610612747,11.00,3.00,0.000,29.0000,106.400
20,255.0,3.0,144.0,10.0,3.0,0.0,2000-01,8.0,34.0,0.0,...,"42.982923, -71.446094",shot - 20,NaN,20000019,1610612747,10.00,3.00,0.000,8.0000,34.000
22,274.0,-16.0,110.0,7.0,3.0,0.0,2000-01,57.0,31.0,1.0,...,"42.982923, -71.446094",shot - 44,NaN,20000019,1610612747,7.00,3.00,0.000,57.0000,31.000
23,299.0,-109.0,150.0,5.0,3.0,0.0,NaN,47.0,38.0,1.0,...,"42.982923, -71.446094",NaN,shot - 3,20000019,1610612747,5.00,3.00,0.000,47.0000,38.000
24,307.0,-46.0,63.0,5.0,3.0,0.0,2000-01,11.0,27.0,1.0,...,"42.982923, -71.446094",NaN,shot - 3,20000019,1610612747,5.00,3.00,0.000,25.2000,27.000
25,332.0,0.0,0.0,2.0,3.0,0.0,2000-01,36.0,20.0,0.0,...,"42.982923, -71.446094",NaN,shot - 4,20000019,1610612747,93.64,3.00,0.000,36.0000,20.000
26,345.0,NaN,196.0,2.0,3.0,0.0,2000-01,4.0,40.0,0.0,...,"42.982923, -71.446094",shot - 30,NaN,20000019,1610612747,2.00,83.36,0.000,63.7856,40.000
27,369.0,-183.0,186.0,0.0,3.0,0.0,2000-01,30.0,46.0,0.0,...,"42.982923, -71.446094",shot - 54,NaN,20000019,1610612747,0.00,3.00,0.000,30.0000,53.400
28,400.0,85.0,173.0,8.0,4.0,0.0,2000-01,NaN,39.0,0.0,...,"42.982923, -71.446094",NaN,shot - 3,20000019,1610612747,8.00,4.00,61.928,19.0000,18.400
29,429.0,3.0,87.0,6.0,4.0,0.0,2000-01,22.0,28.0,0.0,...,"42.982923, -71.446094",shot - 42,NaN,20000019,1610612747,73.64,4.00,0.000,22.0000,28.000
30,488.0,121.0,4.0,1.0,4.0,0.0,2000-01,20.0,NaN,1.0,...,"42.982923, -71.446094",shot - 44,NaN,20000019,1610612747,1.00,4.00,0.000,66.2000,32.000
31,499.0,127.0,34.0,0.0,4.0,0.0,NaN,30.0,33.0,0.0,...,"42.982923, -71.446094",NaN,shot - 3,20000019,1610612747,0.00,4.00,0.000,30.0000,38.400
38,184.0,91.0,184.0,3.0,2.0,0.0,2000-01,30.0,40.0,1.0,...,"49.250068, -123.114646",NaN,shot - 3,20000047,1610612747,3.00,2.00,0.000,30.0000,40.000
39,202.0,-27.0,272.0,0.0,2.0,0.0,2000-01,4.0,47.0,1.0,...,"49.250068, -123.114646",NaN,shot - 3,20000047,1610612747,75.64,2.00,0.000,4.0000,47.000
40,212.0,-176.0,66.0,11.0,3.0,0.0,2000-01,12.0,38.0,0.0,...,"49.250068, -123.114646",NaN,shot - 3,20000047,1610612747,11.00,66.36,36.928,12.0000,57.400
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30657,130.0,158.0,154.0,8.0,2.0,1.0,1999-00,35.0,42.0,1.0,...,"40.361408, -86.186052",NaN,shot - 3,49900087,1610612747,8.00,2.00,1.000,35.0000,42.000
30658,189.0,-44.0,229.0,2.0,2.0,1.0,NaN,59.0,43.0,0.0,...,NaN,shot - 22,NaN,49900087,1610612747,87.64,2.00,1.000,NaN,43.000
30660,238.0,-14.0,18.0,10.0,3.0,1.0,NaN,44.0,22.0,0.0,...,"40.361408, -86.186052",NaN,shot - 4,49900087,1610612747,10.00,3.00,116.928,44.0000,90.400
30661,245.0,0.0,0.0,9.0,3.0,1.0,1999-00,58.0,20.0,1.0,...,"40.361408, -86.186052",NaN,shot - 1,49900087,1610612747,9.00,3.00,1.000,76.2000,20.000
30662,259.0,-8.0,NaN,8.0,3.0,1.0,1999-00,32.0,25.0,0.0,...,"40.361408, -86.186052",NaN,shot - 3,49900087,1610612747,8.00,76.36,NaN,32.0000,25.000
30663,270.0,NaN,25.0,6.0,3.0,1.0,1999-00,36.0,30.0,0.0,...,"40.361408, -86.186052",shot - 55,NaN,49900087,1610612747,6.00,3.00,1.000,36.0000,30.000
30665,280.0,-14.0,18.0,5.0,3.0,NaN,NaN,58.0,22.0,0.0,...,"40.361408, -86.186052",NaN,shot - 4,49900087,1610612747,84.20,3.00,1.000,58.0000,22.000
30666,295.0,-81.0,171.0,4.0,3.0,1.0,1999-00,NaN,38.0,0.0,...,"40.361408, -86.186052",NaN,shot - 3,49900087,1610612747,63.64,3.00,1.000,4.0000,21.400
30667,368.0,40.0,250.0,9.0,4.0,1.0,1999-00,33.0,45.0,0.0,...,"40.361408, -86.186052",NaN,shot - 3,49900087,1610612747,9.00,4.00,1.000,33.0000,NaN
30669,425.0,171.0,53.0,3.0,4.0,1.0,NaN,48.0,37.0,0.0,...,"40.361408, -86.186052",NaN,shot - 3,49900087,1610612747,3.00,4.00,1.000,112.7856,37.000
30670,NaN,-74.0,16.0,9.0,1.0,1.0,1999-00,34.0,27.0,0.0,...,"42.982923, -71.446094",NaN,shot - 3,49900088,1610612747,38.64,1.00,1.000,34.0000,27.000
30671,25.0,0.0,0.0,8.0,1.0,1.0,1999-00,51.0,20.0,0.0,...,"42.982923, -71.446094",NaN,shot - 4,49900088,1610612747,8.00,102.36,1.000,51.0000,20.000
30672,29.0,89.0,55.0,8.0,1.0,1.0,1999-00,9.0,30.0,1.0,...,"42.982923, -71.446094",shot - 33,NaN,49900088,1610612747,109.64,29.36,1.000,9.0000,30.000
30673,NaN,117.0,0.0,NaN,1.0,1.0,NaN,14.0,31.0,0.0,...,"42.982923, -71.446094",NaN,shot - 3,49900088,1610612747,7.00,63.36,1.000,14.0000,31.000
30674,81.0,117.0,216.0,2.0,1.0,1.0,1999-00,34.0,44.0,1.0,...,"42.982923, -71.446094",NaN,shot - 3,49900088,1610612747,2.00,1.00,1.000,34.0000,44.000
30675,84.0,-134.0,NaN,2.0,1.0,1.0,NaN,0.0,45.0,0.0,...,"42.982923, -71.446094",NaN,shot - 3,49900088,1610612747,2.00,1.00,34.928,0.0000,45.000
30676,98.0,-141.0,0.0,0.0,1.0,1.0,1999-00,NaN,34.0,1.0,...,"42.982923, -71.446094",shot - 44,NaN,49900088,1610612747,0.00,1.00,1.000,37.0000,34.000
30677,101.0,NaN,143.0,0.0,1.0,1.0,1999-00,1.0,38.0,0.0,...,"42.982923, -71.446094",NaN,shot - 3,49900088,1610612747,0.00,1.00,1.000,1.0000,38.000
30678,181.0,14.0,16.0,3.0,2.0,NaN,1999-00,34.0,NaN,0.0,...,"42.982923, -71.446094",NaN,shot - 4,49900088,1610612747,3.00,29.36,1.000,34.0000,22.000
30683,228.0,1.0,216.0,10.0,NaN,1.0,1999-00,51.0,41.0,0.0,...,"42.982923, -71.446094",shot - 38,NaN,49900088,1610612747,10.00,3.00,1.000,51.0000,41.000
30684,231.0,-96.0,89.0,10.0,3.0,1.0,NaN,16.0,33.0,0.0,...,"42.982923, -71.446094",shot - 37,NaN,49900088,1610612747,50.64,3.00,1.000,16.0000,NaN
30685,249.0,81.0,250.0,7.0,3.0,NaN,1999-00,31.0,46.0,0.0,...,"42.982923, -71.446094",NaN,shot - 3,49900088,1610612747,7.00,3.00,44.608,31.0000,46.000
30688,308.0,-126.0,61.0,1.0,3.0,1.0,1999-00,7.0,33.0,1.0,...,"42.982923, -71.446094",NaN,shot - 3,49900088,1610612747,37.64,NaN,1.000,7.0000,16.400
30689,326.0,-12.0,679.0,0.0,3.0,1.0,1999-00,0.0,87.0,0.0,...,"42.982923, -71.446094",NaN,shot - 3,49900088,1610612747,NaN,31.60,1.000,0.0000,45.728
30690,331.0,-113.0,100.0,11.0,4.0,1.0,1999-00,37.0,35.0,0.0,...,"42.982923, -71.446094",NaN,shot - 3,49900088,1610612747,11.00,23.36,1.000,37.0000,35.000
30691,382.0,0.0,0.0,NaN,4.0,1.0,1999-00,4.0,20.0,0.0,...,"42.982923, -71.446094",shot - 4,NaN,49900088,1610612747,7.00,4.00,27.800,59.7856,20.000
30692,397.0,1.0,48.0,6.0,4.0,1.0,1999-00,5.0,24.0,0.0,...,"42.982923, -71.446094",shot - 1,NaN,49900088,1610612747,17.20,4.00,1.000,5.0000,24.000
30694,426.0,-134.0,166.0,3.0,4.0,1.0,1999-00,28.0,41.0,1.0,...,NaN,NaN,shot - 3,49900088,1610612747,3.00,4.00,1.000,28.0000,41.000
30695,448.0,31.0,267.0,2.0,4.0,1.0,1999-00,10.0,46.0,0.0,...,"42.982923, -71.446094",shot - 26,NaN,49900088,1610612747,2.00,112.36,1.000,10.0000,46.000
30696,471.0,1.0,NaN,0.0,4.0,1.0,1999-00,39.0,27.0,0.0,...,"42.982923, -71.446094",shot - 45,NaN,49900088,1610612747,0.00,4.00,1.000,39.0000,27.000

In [4]:
data_train_test_combined.dropna(axis=0,subset=['is_goal'],inplace=True) #Not required
y = data_train_test_combined.is_goal
X = data_train_test_combined.drop(['is_goal'],axis =1 ) #.select_dtypes(exclude =['object'])

D:\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [10]:
train_X,test_X,train_y,test_y = train_test_split(X,y,test_size=0.25)
X_test = test_file.drop(['is_goal'],axis =1)

In [12]:
from sklearn.impute import SimpleImputer
my_imputer = SimpleImputer()
imputed_X_train = my_imputer.fit_transform(train_X.select_dtypes(exclude='object'))
imputed_X_valid = my_imputer.transform(test_X.select_dtypes(exclude='object'))
imputed_final_test = my_imputer.transform(X_test.select_dtypes(exclude='object'))

In [15]:
# pd.DataFrame(imputed_X_train,columns=train_X.select_dtypes(exclude ='object').columns) #imputer return numpy ndarray
# pd.DataFrame(imputed_X_train)

# pd.DataFrame(imputed_X_train,columns=train_X.select_dtypes(exclude ='object').columns)

In [16]:
# All categorical columns
object_cols = [col for col in train_X.columns if train_X[col].dtype == "object"]

# Columns that can be safely label encoded
good_label_cols = [col for col in object_cols if 
                   set(train_X[col]) == set(X_test[col])]
        
# Problematic columns that will be dropped from the dataset
bad_label_cols =  list (set(object_cols) - set(good_label_cols))
        
print('Categorical columns that will be label encoded:', good_label_cols)
print('\nCategorical columns that will be dropped from the dataset:', bad_label_cols)

Categorical columns that will be label encoded: ['game_season', 'area_of_shot', 'shot_basics', 'range_of_shot', 'team_name', 'home/away', 'lat/lng', 'type_of_shot', 'type_of_combined_shot']

Categorical columns that will be dropped from the dataset: ['date_of_game']

In [19]:
# Label Encoding 
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
# Drop categorical columns that will not be encoded
label_X_train = train_X.drop(bad_label_cols, axis=1)
label_X_valid = test_X.drop(bad_label_cols, axis=1)
label_final_X_test = X_test.drop(bad_label_cols,axis=1)

# Apply label encoder 
label_encoder = LabelEncoder()


for col in set(good_label_cols):
    label_X_train[col] = label_encoder.fit_transform(label_X_train[col].astype(str))
    label_X_valid[col] = label_encoder.transform(label_X_valid[col].astype(str))
    label_final_X_test[col] = label_encoder.transform(label_final_X_test[col].astype(str))

In [22]:
Numerical = pd.DataFrame(imputed_X_train,columns=train_X.select_dtypes(exclude ='object').columns)
Numerical_V = pd.DataFrame(imputed_X_valid,columns=test_X.select_dtypes(exclude='object').columns)
Numerical_T = pd.DataFrame(imputed_final_test,columns=X_test.select_dtypes(exclude='object').columns)
Numerical_T.columns

Index(['match_event_id', 'location_x', 'location_y', 'remaining_min',
       'power_of_shot', 'knockout_match', 'remaining_sec', 'distance_of_shot',
       'shot_id_number', 'match_id', 'team_id', 'remaining_min.1',
       'power_of_shot.1', 'knockout_match.1', 'remaining_sec.1',
       'distance_of_shot.1'],
      dtype='object')

In [26]:
Categorical = label_X_train[good_label_cols]
Categorical_V = label_X_valid[good_label_cols]
Categorical_T = label_final_X_test[good_label_cols]
Categorical.columns

Index(['game_season', 'area_of_shot', 'shot_basics', 'range_of_shot',
       'team_name', 'home/away', 'lat/lng', 'type_of_shot',
       'type_of_combined_shot'],
      dtype='object')

In [31]:
#model_train_x = pd.concat([label_X_train[good_label_cols],imputed_X_train],ignore_index=True,sort=False)
# pd.concat([data1, data2], ignore_index=True, sort =False)
Model_train_X = pd.concat([Numerical.reset_index() ,Categorical.reset_index() ],ignore_index=True,sort=False,axis=1) # Number of rows were increasing
Model_valid_X = pd.concat([Numerical_V.reset_index(),Categorical_V.reset_index()],ignore_index=True,sort=False,axis=1) 
Model_test_X = pd.concat([Numerical_T.reset_index(),Categorical_T.reset_index()],ignore_index=True,sort=False,axis=1)
Model_train_X.shape

(18321, 27)

In [32]:

my_model = XGBRegressor(n_estimators=1000)
my_model.fit(Model_train_X,train_y)
from sklearn.metrics import mean_absolute_error
mean_absolute_error(my_model.predict(Model_valid_X),test_y)

D:\Anaconda3\lib\site-packages\xgboost\core.py:587: FutureWarning: Series.base is deprecated and will be removed in a future version
  if getattr(data, 'base', None) is not None and \

[17:05:44] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.

0.4485757215718233

In [33]:
my_model = XGBRegressor(n_estimators=1000)
my_model.fit(label_X_train[good_label_cols],train_y)
from sklearn.metrics import mean_absolute_error
mean_absolute_error(my_model.predict(label_X_valid[good_label_cols]),test_y)
#ans = my_model.predict(label_final_X_test[good_label_cols])
# ans[:5]

D:\Anaconda3\lib\site-packages\xgboost\core.py:587: FutureWarning: Series.base is deprecated and will be removed in a future version
  if getattr(data, 'base', None) is not None and \

[17:06:25] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.

0.44795297228224384

Debug Area**Add Statements to see results**

In [34]:
test_preds = my_model.predict(label_final_X_test[good_label_cols])
output = pd.DataFrame({'shot_id_number': X_test['shot_id_number'],
                       'is_goal': test_preds})
output.loc[output['is_goal'] < 0,'is_goal'] = 0
output.to_csv('submission.csv',index=False)

In [35]:
ans = pd.read_csv('submission.csv')

In [36]:


ans[ans['is_goal'] < 0]

Empty DataFrame
Columns: [shot_id_number, is_goal]
Index: []

In [37]:
ans.describe()

       shot_id_number      is_goal
count     6268.000000  6268.000000
mean     15423.616784     0.450407
std       8864.689203     0.168322
min          1.000000     0.000000
25%       7766.750000     0.345801
50%      15396.500000     0.414528
75%      23182.750000     0.523953
max      30694.000000     1.257898

In [38]:
ans

      shot_id_number   is_goal
0                  1  0.338307
1                  8  0.488324
2                 17  0.590040
3                 20  0.623545
4                 22  0.422838
5                 33  0.394658
6                 34  0.526026
7                 35  0.536782
8                 36  0.536782
9                 37  0.597257
10                38  0.367987
11                45  0.536782
12                50  0.439404
13                55  0.269418
14                60  0.288219
15                62  0.298776
16                66  0.393790
17                67  0.277253
18                71  0.594435
19                72  0.308961
20                76  0.435180
21                80  0.286178
22                85  0.346150
23                86  0.408917
24                87  0.295523
25                92  0.193225
26                95  0.414665
27                97  0.238640
28               104  0.607367
29               113  0.386228
...              ...       ...
6238           30568  0.428833
6239           30570  0.931992
6240           30581  0.325433
6241           30584  0.426183
6242           30591  0.409620
6243           30594  0.619707
6244           30614  0.237290
6245           30617  0.340265
6246           30618  0.748437
6247           30626  0.329393
6248           30630  0.364245
6249           30631  0.299079
6250           30632  0.384188
6251           30634  0.356511
6252           30636  0.600521
6253           30637  0.758915
6254           30639  0.395230
6255           30647  0.399252
6256           30649  0.413559
6257           30656  0.384188
6258           30660  0.350223
6259           30665  0.287551
6260           30669  0.402176
6261           30680  0.373507
6262           30681  0.347033
6263           30682  0.263527
6264           30683  0.808075
6265           30687  0.751013
6266           30688  0.179461
6267           30694  0.434370

[6268 rows x 2 columns]